menu:
#- {name: 'people', url: '/people'}
- {name: 'step-by-step', url: '/blog'}
- {name: 'codes', url: '/codes'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

codes:
- {name: 'Computing the properties of a quarter circle', url: 'quarter-circle'}
- {name: 'Optimization Methods', url: 'optimization-methods'}
- {name: 'Quarter circle', url: 'https://github.com/RenanMP12/python-codes/blob/main/Circular%20geometry.py'}

#- {name: 'Stellar Structures', url: 'stellar-structures'}

finite_element:
- {name: 'Quarter circle geometric properties', url: 'https://github.com/RenanMP12/python-codes/blob/main/Circular%20geometry.py'}
- {name: 'Collocation Method', url: 'https://github.com/RenanMP12/python-codes/blob/main/collocation_method.py'}
- {name: 'Galerkin Method', url: 'https://github.com/RenanMP12/python-codes/blob/main/galerkin_method.py'}
- {name: '2D Euler-Bernoulli Beam under Quadratic Load', url: 'https://github.com/RenanMP12/python-codes/blob/main/2D%20Euler%20Beam%20Quadratic%20Load.py'}
- {name: 'Critical Load on Column', url: 'https://github.com/RenanMP12/python-codes/blob/main/euler_critical_load.py'}
- {name: 'Modes of vibration of a beam', url: 'https://github.com/RenanMP12/python-codes/blob/main/modes_vibration_beam.py'}
- {name: '2D Truss', url: 'https://github.com/RenanMP12/python-codes/blob/main/Truss_2D.py'}

optimization:
#- {name: 'Newton-Raphson', url: ''}
#- {name: 'Quasi-Newton', url: ''}


social:
- {icon: 'github', link: 'https://github.com/RenanMP12'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/renan-miranda-portela-215b7940?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BXiZrQtawR%2F6VB2ioVnc60Q%3D%3D'}
- {icon: 'paypal', link: ''}
#[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](YOUR_EMAIL_CODE)

contacts:
- {name: 'Renan Portela', title: 'Ph.D. Student', department: 'Mechanical and Mechatronics Engineering', institution: 'University of Waterloo', institution_address: '200 University Ave W, Waterloo, ON N2L 3G1, Canada', email: 'renan.portela@uwaterloo.ca', image: 'assets/img/IMG-20170606-WA0027.jpg'}
