menu:
#- {name: 'people', url: '/people'}
#- {name: 'publications', url: '/publications'}
- {name: 'codes', url: '/codes'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

codes:
- {name: 'Finite Element Method', url: 'finite-element'}
- {name: 'Optimization Methods', url: 'optimization-methods'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/renan-miranda-portela-215b7940?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BXiZrQtawR%2F6VB2ioVnc60Q%3D%3D'}

contacts:
- {name: 'Renan Portela', title: 'Ph.D. Student', department: 'Mechanical and Mechatronics Engineering', institution: 'University of Waterloo', institution_address: '200 University Ave W, Waterloo, ON N2L 3G1, Canada', phone: '(000) 000-0000', email: 'renan.portela@uwaterloo.ca', office: 'Science Building 505', image: 'assets/img/IMG-20170606-WA0027.jpg'}
